### ISSUE TITLE
Responses to few simple queries.

### ISSUE THREAD

**Issue by rgentyala** [ibm-ecosystem-engineering/SuperKnowa#20]
Instana tracing data?
I'm trying to understand how to use Instana tracing data. I'm assuming that the tracing data is a json file. I'm also assuming that the tracing data is a json file. I'm not sure how to use the tracing data. I've been able to use the json file to get the data I need. I can get the data I need for the java application.

IBM Turbonomic features?
Ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm turbonomic features? ibm.
Reference: [link](url:https://www.ibm.com/docs/en/tarm/8.6.0?topic=tasks-license-configuration)

I think on LLMs, context based responses are key to begin with just like how chatbots work. These responses are pretty simple and we need to have more generic but precise responses.

**Comment by Shivam6693** [comment]
@rgentyala The SuperKnowa pipeline is not currently tuned to answer phrase (half-baked) questions. It works when you enter the full text natural language query as shown here:
![Screenshot 2023-09-06 at 3 21 11 PM](https://github.com/ibm-ecosystem-engineering/SuperKnowa/assets/40213210/473b0320-de4a-4ab1-a954-9cf8b53600a5)


![Screenshot 2023-09-06 at 3 22 24 PM](https://github.com/ibm-ecosystem-engineering/SuperKnowa/assets/40213210/5d987a3c-ea20-4494-8a63-8a1b1124518e)
