### ISSUE TITLE
MFA

### ISSUE THREAD

**Issue by rgentyala** [ibm-ecosystem-engineering/SuperKnowa#21]
IBM MFA is really showing a code version that is received through IBM Verify but this should exactly work similar to MFA for W3. Email MFA is working but IBM Verify needs "touch approval" etc. Please review MFA.

**Comment by biharicoder** [comment]
@htalukderibm I think this issue is resolved now, right?

**Comment by htalukderibm** [comment]
![image](https://github.com/ibm-ecosystem-engineering/SuperKnowa/assets/111310676/62b9b49b-5133-4331-a8d8-a1d152b53a84)

@biharicoder Yes issue is resolved right now.
