### ISSUE TITLE
unable to answer simple question

### ISSUE THREAD

**Issue by magnumhell** [ibm-ecosystem-engineering/SuperKnowa#24]
```
What is watson knowledge catalog?
The information you are looking for is not available. Please try again later. Thank you.
```

<img width="1728" alt="image" src="https://github.com/ibm-ecosystem-engineering/SuperKnowa/assets/37954690/67b1a06d-a321-403e-8fc7-1cbb3e8af680">

**Comment by kunal-savvy** [comment]
the BAM server is currently down ... @Shivam6693 plz update once app is back

**Comment by Shivam6693** [comment]
@magnumhell The issue has been resolved.
![Screenshot 2023-09-22 at 7 24 59 AM](https://github.com/ibm-ecosystem-engineering/SuperKnowa/assets/40213210/9b8e1f0e-532f-4fa6-be6b-d5d2693b7c1b)
