### ISSUE TITLE
Example question not working. please kindly help take a look?

### ISSUE THREAD

**Issue by liutiez** [ibm-ecosystem-engineering/SuperKnowa#30]
Example question not working. please kindly help take a look?

> Can Instana use OpenTelemetry trace data?

<img width="712" alt="image" src="https://github.com/ibm-ecosystem-engineering/SuperKnowa/assets/34931532/b78a4ce1-d50c-4532-84f6-c6c4de525254">

**Comment by Shivam6693** [comment]
@liutiez The Elasticsearch instance had an issue, which prevented SuperKnowa from working. The ES instance has been restored and is now generating answers. Thanks! 
<img width="1149" alt="Screenshot 2024-04-11 at 3 49 35 PM" src="https://github.com/ibm-ecosystem-engineering/SuperKnowa/assets/40213210/07ec987e-18c0-48d4-925c-234fe7a7e923">
